/**
 * mockData.ts — 10개 다양한 템플릿 (gesture / voice_read / timing / expression)
 */
import type { Template } from '../types/template';
import type { UserSession, UserProfile } from '../types/session';

export const MOCK_TEMPLATES: Template[] = [

  // ─── 1. 일상 브이로그 (daily_vlog) ───────────────────────────────────────
  {
    id: 'daily-vlog-001',
    name: '오늘의 브이로그',
    genre: 'daily',
    theme_id: 'daily',
    camera_mode: 'selfie',
    difficulty: 1,
    duration_sec: 15,
    bpm: 100,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '📱',
    scene: '오늘 하루를 셀카로 기록해보세요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #667eea 0%, #764ba2 100%)',
      frameColor: '#9b59b6',
    },
    sns_template: {
      hashtags: ['일상브이로그', '오늘하루', '일상기록', 'dailyvlog', '브이로그'],
      caption_template: '오늘도 기분 좋은 하루 🌟 {template_name} 점수 {score}점! #일상 #vlog',
      video_frame_css: 'border: 3px solid #9b59b6; border-radius: 16px;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 3000,  text: '👋 안녕하세요~!',         style: 'highlight' },
      { start_ms: 3000,  end_ms: 7000,  text: '💝 오늘도 좋은 하루!',     style: 'bold' },
      { start_ms: 7000,  end_ms: 11000, text: '✌️ 오늘의 브이로그!',      style: 'normal' },
      { start_ms: 11000, end_ms: 15000, text: '❤️ 구독 좋아요 눌러줘요!', style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 3500,
        type: 'gesture', gesture_id: 'wave', gesture_emoji: '👋',
        threshold: 0.6, guide_text: '손 흔들어 인사!', guide_emoji: '👋', anim_type: 'float',
      },
      {
        seq: 2, start_ms: 3500, end_ms: 7500,
        type: 'gesture', gesture_id: 'heart', gesture_emoji: '💝',
        threshold: 0.65, guide_text: '하트 만들기!', guide_emoji: '💝', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 7500, end_ms: 11500,
        type: 'gesture', gesture_id: 'v_sign', gesture_emoji: '✌️',
        threshold: 0.6, guide_text: 'V 사인!', guide_emoji: '✌️', anim_type: 'bounce',
      },
      {
        seq: 4, start_ms: 11500, end_ms: 15000,
        type: 'gesture', gesture_id: 'thumbs_up', gesture_emoji: '👍',
        threshold: 0.65, guide_text: '엄지 척!', guide_emoji: '👍', anim_type: 'bounce',
      },
    ],
  },

  // ─── 2. 뉴스 앵커 (news_anchor) ───────────────────────────────────────────
  {
    id: 'news-anchor-002',
    name: '뉴스 앵커 챌린지',
    genre: 'news',
    theme_id: 'news',
    camera_mode: 'selfie',
    difficulty: 2,
    duration_sec: 25,
    bpm: 90,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '📺',
    scene: '뉴스 스튜디오에서 앵커가 되어봐요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'pattern',
      css: 'linear-gradient(180deg, #0a1628 0%, #1a2e4a 50%, #0d1f35 100%)',
      overlayTop: '📺 LIVE NEWS',
      overlayBottom: '🔴 속보 · 오늘의 뉴스 · BREAKING NEWS · 최신 뉴스 · ',
      frameColor: '#1565c0',
    },
    sns_template: {
      hashtags: ['뉴스앵커', '챌린지', '뉴스스타', 'newsanchor', '앵커챌린지'],
      caption_template: '내가 뉴스 앵커가 됐어요! 📺 {template_name} {score}점 달성! #뉴스앵커 #챌린지',
      video_frame_css: 'border: 3px solid #1565c0; border-radius: 8px; background: #0a1628;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 4000,  text: '📺 안녕하세요. 뉴스 시작합니다.', style: 'news' },
      { start_ms: 4000,  end_ms: 10000, text: '오늘의 주요 뉴스를 전해드리겠습니다.', style: 'news' },
      { start_ms: 10000, end_ms: 17000, text: '전국적으로 맑겠으며 기온은 25도까지 오르겠습니다.', style: 'news' },
      { start_ms: 17000, end_ms: 25000, text: '이상으로 오늘의 뉴스를 마치겠습니다. 감사합니다.', style: 'news' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 5000,
        type: 'timing',
        threshold: 0.6, guide_text: '카메라를 정면으로 바라봐요', guide_emoji: '📷', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 5000, end_ms: 12000,
        type: 'voice_read',
        read_text: '안녕하세요, 오늘의 주요 뉴스를 전해드리겠습니다.',
        read_lang: 'ko',
        threshold: 0.55, guide_text: '앵커처럼 읽어보세요!', guide_emoji: '🎙️', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 12000, end_ms: 19000,
        type: 'voice_read',
        read_text: '오늘 날씨는 전국적으로 맑겠으며, 기온은 25도까지 오르겠습니다.',
        read_lang: 'ko',
        threshold: 0.5, guide_text: '날씨 예보를 읽어요!', guide_emoji: '🌤️', anim_type: 'pulse',
      },
      {
        seq: 4, start_ms: 19000, end_ms: 25000,
        type: 'voice_read',
        read_text: '이상으로 오늘의 뉴스를 마치겠습니다. 감사합니다.',
        read_lang: 'ko',
        threshold: 0.55, guide_text: '마무리 멘트!', guide_emoji: '🎬', anim_type: 'float',
      },
    ],
  },

  // ─── 3. 영어 레슨 (english_lesson) ───────────────────────────────────────
  {
    id: 'english-lesson-003',
    name: '영어 한마디 챌린지',
    genre: 'english',
    theme_id: 'english',
    camera_mode: 'selfie',
    difficulty: 2,
    duration_sec: 20,
    bpm: 95,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🇺🇸',
    scene: '영어 문장을 자신있게 읽어봐요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%)',
      overlayTop: '🇺🇸 English Challenge',
      frameColor: '#2196f3',
    },
    sns_template: {
      hashtags: ['영어챌린지', '영어공부', 'englishchallenge', '영어한마디', 'speakenglish'],
      caption_template: '영어 말하기 도전! 🇺🇸 {template_name} {score}점! 나도 영어 할 수 있어! #영어챌린지',
      video_frame_css: 'border: 3px solid #2196f3; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 4000,  text: '🇺🇸 영어로 말해봐요!',         style: 'bold' },
      { start_ms: 4000, end_ms: 10000, text: 'Hello everyone! Today is a wonderful day.', style: 'highlight' },
      { start_ms: 10000,end_ms: 16000, text: 'I love learning English every day!',        style: 'highlight' },
      { start_ms: 16000,end_ms: 20000, text: 'See you next time! Bye bye! 👋',            style: 'bold' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 4000,
        type: 'gesture', gesture_id: 'wave', gesture_emoji: '👋',
        threshold: 0.6, guide_text: '손 흔들어 인사!', guide_emoji: '👋', anim_type: 'bounce',
      },
      {
        seq: 2, start_ms: 4000, end_ms: 11000,
        type: 'voice_read',
        read_text: 'Hello everyone! Today is a wonderful day.',
        read_lang: 'en',
        threshold: 0.5, guide_text: '영어로 읽어봐요!', guide_emoji: '🗣️', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 11000, end_ms: 17000,
        type: 'voice_read',
        read_text: 'I love learning English every day!',
        read_lang: 'en',
        threshold: 0.5, guide_text: '자신있게!', guide_emoji: '💪', anim_type: 'pulse',
      },
      {
        seq: 4, start_ms: 17000, end_ms: 20000,
        type: 'gesture', gesture_id: 'wave', gesture_emoji: '👋',
        threshold: 0.6, guide_text: '작별 인사!', guide_emoji: '👋', anim_type: 'bounce',
      },
    ],
  },

  // ─── 4. 동화 낭독 (fairy_tale_reader) ────────────────────────────────────
  {
    id: 'fairy-tale-004',
    name: '동화책 낭독 챌린지',
    genre: 'kids',
    theme_id: 'fairy_tale',
    camera_mode: 'selfie',
    difficulty: 1,
    duration_sec: 20,
    bpm: 80,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '📖',
    scene: '동화책 주인공이 되어 낭독해봐요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'pattern',
      css: 'linear-gradient(135deg, #ffecd2 0%, #fcb69f 100%)',
      overlayTop: '📖 옛날 옛날에...',
      frameColor: '#ff9800',
    },
    sns_template: {
      hashtags: ['동화낭독', '동화챌린지', '동화책', '낭독챌린지', 'storytelling'],
      caption_template: '나만의 동화 낭독 🏰 {template_name} {score}점 달성! #동화 #낭독챌린지',
      video_frame_css: 'border: 4px solid #ff9800; border-radius: 20px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 3000,  text: '📖 옛날 옛날에...',                           style: 'story' },
      { start_ms: 3000, end_ms: 10000, text: '숲속 깊은 곳에 작은 오두막이 있었어요.',        style: 'story' },
      { start_ms: 10000,end_ms: 17000, text: '그곳에는 마음씨 착한 소녀가 살고 있었답니다.',  style: 'story' },
      { start_ms: 17000,end_ms: 20000, text: '이야기는 계속됩니다... 🌙',                    style: 'story' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 4000,
        type: 'expression',
        threshold: 0.6, guide_text: '이야기 시작 표정!', guide_emoji: '😊', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 4000, end_ms: 11000,
        type: 'voice_read',
        read_text: '옛날 옛적에 숲속 깊은 곳에 작은 오두막이 있었어요.',
        read_lang: 'ko',
        threshold: 0.5, guide_text: '동화처럼 읽어봐요!', guide_emoji: '📖', anim_type: 'float',
      },
      {
        seq: 3, start_ms: 11000, end_ms: 18000,
        type: 'voice_read',
        read_text: '그곳에는 마음씨 착한 소녀가 살고 있었답니다.',
        read_lang: 'ko',
        threshold: 0.5, guide_text: '계속 이야기해요!', guide_emoji: '🏡', anim_type: 'float',
      },
      {
        seq: 4, start_ms: 18000, end_ms: 20000,
        type: 'gesture', gesture_id: 'heart', gesture_emoji: '💕',
        threshold: 0.6, guide_text: '해피엔딩 하트!', guide_emoji: '💕', anim_type: 'pulse',
      },
    ],
  },

  // ─── 5. 여행 인증 (travel_cert) ───────────────────────────────────────────
  {
    id: 'travel-cert-005',
    name: '여행지 인증 챌린지',
    genre: 'travel',
    theme_id: 'travel',
    camera_mode: 'normal',
    difficulty: 1,
    duration_sec: 15,
    bpm: 110,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '✈️',
    scene: '여행지, 핫플, 카페 앞에서 인증해봐요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #0099f7 0%, #f11712 100%)',
      overlayTop: '✈️ TRAVEL CERT',
      frameColor: '#00bcd4',
    },
    sns_template: {
      hashtags: ['여행인증', '여행스타그램', '핫플', 'travelgram', '여행챌린지'],
      caption_template: '여기 왔어요! ✈️ {template_name} {score}점! 강추 여행지 #여행인증 #여행스타그램',
      video_frame_css: 'border: 3px solid #00bcd4; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 3500,  text: '✈️ 어디야? 배경 보여줘!',   style: 'bold' },
      { start_ms: 3500, end_ms: 7000,  text: '✌️ 여기 왔어요~',           style: 'highlight' },
      { start_ms: 7000, end_ms: 11000, text: '📸 인증샷 찍어줘!',          style: 'normal' },
      { start_ms: 11000,end_ms: 15000, text: '🙌 여기 강추입니다!!',        style: 'bold' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 3500,
        type: 'timing',
        threshold: 0.6, guide_text: '배경 보여줘!', guide_emoji: '🌍', anim_type: 'float',
      },
      {
        seq: 2, start_ms: 3500, end_ms: 7500,
        type: 'gesture', gesture_id: 'v_sign', gesture_emoji: '✌️',
        threshold: 0.65, guide_text: 'V 사인!', guide_emoji: '✌️', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 7500, end_ms: 11500,
        type: 'gesture', gesture_id: 'point_cam', gesture_emoji: '👉',
        threshold: 0.65, guide_text: '카메라 가리켜!', guide_emoji: '📸', anim_type: 'shake',
      },
      {
        seq: 4, start_ms: 11500, end_ms: 15000,
        type: 'gesture', gesture_id: 'hands_up', gesture_emoji: '🙌',
        threshold: 0.7, guide_text: '양손 번쩍!', guide_emoji: '🙌', anim_type: 'bounce',
      },
    ],
  },

  // ─── 6. 제품 언박싱 (product_unboxing) ───────────────────────────────────
  {
    id: 'product-unbox-006',
    name: '신상템 언박싱 챌린지',
    genre: 'promotion',
    theme_id: 'product',
    camera_mode: 'selfie',
    difficulty: 1,
    duration_sec: 20,
    bpm: 120,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🛍️',
    scene: '새로 산 아이템을 카메라 앞에서 소개해요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #f093fb 0%, #f5576c 100%)',
      frameColor: '#e91e63',
    },
    sns_template: {
      hashtags: ['언박싱', '신상템', '제품리뷰', 'unboxing', '쇼핑스타그램'],
      caption_template: '신상 언박싱 완료 🛍️ {template_name} {score}점! 이거 진짜 강추!! #언박싱 #신상',
      video_frame_css: 'border: 3px solid #e91e63; border-radius: 16px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 4000,  text: '🛍️ 이거 봐봐요!!!',       style: 'bold' },
      { start_ms: 4000, end_ms: 8000,  text: '👆 두두등장~',             style: 'highlight' },
      { start_ms: 8000, end_ms: 13000, text: '😍 완전 대박이에요',        style: 'normal' },
      { start_ms: 13000,end_ms: 17000, text: '👍 이거 진짜 강추!!',       style: 'bold' },
      { start_ms: 17000,end_ms: 20000, text: '🤩 구경 와줘서 감사해요~', style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 4500,
        type: 'gesture', gesture_id: 'arms_spread', gesture_emoji: '🙆',
        threshold: 0.65, guide_text: '두 팔 벌려 등장!', guide_emoji: '🙆', anim_type: 'bounce',
      },
      {
        seq: 2, start_ms: 4500, end_ms: 8500,
        type: 'gesture', gesture_id: 'hands_up', gesture_emoji: '🙌',
        threshold: 0.68, guide_text: '아이템 번쩍!', guide_emoji: '🙌', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 8500, end_ms: 13000,
        type: 'expression',
        threshold: 0.65, guide_text: '감탄하는 표정!', guide_emoji: '😍', anim_type: 'pulse',
      },
      {
        seq: 4, start_ms: 13000, end_ms: 17000,
        type: 'gesture', gesture_id: 'thumbs_up', gesture_emoji: '👍',
        threshold: 0.7, guide_text: '엄지 척!', guide_emoji: '👍', anim_type: 'bounce',
      },
      {
        seq: 5, start_ms: 17000, end_ms: 20000,
        type: 'gesture', gesture_id: 'wave', gesture_emoji: '👋',
        threshold: 0.65, guide_text: '손 흔들며 마무리!', guide_emoji: '👋', anim_type: 'bounce',
      },
    ],
  },

  // ─── 7. K-POP 챌린지 (kpop_challenge) ────────────────────────────────────
  {
    id: 'kpop-challenge-007',
    name: 'K-POP 댄스 챌린지',
    genre: 'kpop',
    theme_id: 'kpop',
    camera_mode: 'selfie',
    difficulty: 2,
    duration_sec: 20,
    bpm: 130,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🎤',
    scene: 'K-POP 스타가 되어 챌린지!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'pattern',
      css: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
      overlayTop: '🎤 K-POP CHALLENGE',
      frameColor: '#e94560',
    },
    sns_template: {
      hashtags: ['kpop챌린지', 'kpopchallenge', '케이팝', '댄스챌린지', 'kpop'],
      caption_template: '나도 K-POP 스타! 🎤 {template_name} {score}점 달성! 같이 춰요~ #kpop #댄스챌린지',
      video_frame_css: 'border: 3px solid #e94560; border-radius: 12px; background: #1a1a2e;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 4000,  text: '🎤 준비됐어요?',            style: 'bold' },
      { start_ms: 4000, end_ms: 8000,  text: '🙌 양손 번쩍!',             style: 'highlight' },
      { start_ms: 8000, end_ms: 13000, text: '💃 팔 넓게 벌려봐요~',      style: 'normal' },
      { start_ms: 13000,end_ms: 17000, text: '🤍 하트 포즈!',             style: 'bold' },
      { start_ms: 17000,end_ms: 20000, text: '✌️ 마지막 V!',              style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 4000,
        type: 'timing',
        threshold: 0.6, guide_text: '카메라 정면!', guide_emoji: '🎬', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 4000, end_ms: 8000,
        type: 'gesture', gesture_id: 'hands_up', gesture_emoji: '🙌',
        threshold: 0.72, guide_text: '양손 번쩍!', guide_emoji: '🙌', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 8000, end_ms: 13000,
        type: 'gesture', gesture_id: 'arms_spread', gesture_emoji: '🦅',
        threshold: 0.68, guide_text: '양팔 펼쳐요!', guide_emoji: '🦅', anim_type: 'float',
      },
      {
        seq: 4, start_ms: 13000, end_ms: 17000,
        type: 'gesture', gesture_id: 'heart', gesture_emoji: '💝',
        threshold: 0.7, guide_text: '하트 만들어!', guide_emoji: '💝', anim_type: 'pulse',
      },
      {
        seq: 5, start_ms: 17000, end_ms: 20000,
        type: 'gesture', gesture_id: 'v_sign', gesture_emoji: '✌️',
        threshold: 0.68, guide_text: 'V 포즈!', guide_emoji: '✌️', anim_type: 'bounce',
      },
    ],
  },

  // ─── 8. 음식 리뷰 (food_review) ───────────────────────────────────────────
  {
    id: 'food-review-008',
    name: '맛집 리뷰 챌린지',
    genre: 'daily',
    theme_id: 'food',
    camera_mode: 'normal',
    difficulty: 1,
    duration_sec: 15,
    bpm: 95,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🍜',
    scene: '맛있는 음식 앞에서 리뷰해봐요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #f6d365 0%, #fda085 100%)',
      overlayTop: '🍜 FOOD REVIEW',
      frameColor: '#ff5722',
    },
    sns_template: {
      hashtags: ['맛집리뷰', '음식스타그램', '먹스타그램', 'foodreview', '맛집'],
      caption_template: '진짜 맛집 발견! 🍜 {template_name} {score}점! 여기 꼭 오세요~ #맛집 #먹스타그램',
      video_frame_css: 'border: 3px solid #ff5722; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 3500,  text: '🍜 여기 진짜 맛집이에요!!',  style: 'bold' },
      { start_ms: 3500, end_ms: 7500,  text: '😋 맛이 어떠냐고요?',        style: 'highlight' },
      { start_ms: 7500, end_ms: 11000, text: '👍 완전 맛있어요!!!',         style: 'bold' },
      { start_ms: 11000,end_ms: 15000, text: '📍 꼭 와보세요~!',           style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 3500,
        type: 'gesture', gesture_id: 'point_cam', gesture_emoji: '👉',
        threshold: 0.65, guide_text: '음식 가리켜!', guide_emoji: '👉', anim_type: 'shake',
      },
      {
        seq: 2, start_ms: 3500, end_ms: 7500,
        type: 'expression',
        threshold: 0.65, guide_text: '맛있는 표정!', guide_emoji: '😋', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 7500, end_ms: 11000,
        type: 'gesture', gesture_id: 'thumbs_up', gesture_emoji: '👍',
        threshold: 0.7, guide_text: '엄지 척!', guide_emoji: '👍', anim_type: 'bounce',
      },
      {
        seq: 4, start_ms: 11000, end_ms: 15000,
        type: 'gesture', gesture_id: 'wave', gesture_emoji: '👋',
        threshold: 0.65, guide_text: '손 흔들며 마무리!', guide_emoji: '👋', anim_type: 'bounce',
      },
    ],
  },

  // ─── 9. 동기부여 스피치 (motivation_talk) ────────────────────────────────
  {
    id: 'motivation-talk-009',
    name: '동기부여 스피치 챌린지',
    genre: 'daily',
    theme_id: 'motivation',
    camera_mode: 'selfie',
    difficulty: 2,
    duration_sec: 20,
    bpm: 105,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '💪',
    scene: '나를 응원하는 말 한마디!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #4facfe 0%, #00f2fe 100%)',
      overlayTop: '💪 MOTIVATION',
      frameColor: '#00bcd4',
    },
    sns_template: {
      hashtags: ['동기부여', '자기계발', '오늘도화이팅', 'motivation', '긍정에너지'],
      caption_template: '오늘도 화이팅! 💪 {template_name} {score}점! 우리 모두 할 수 있어! #동기부여 #화이팅',
      video_frame_css: 'border: 3px solid #00bcd4; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 4000,  text: '💪 오늘도 할 수 있어!',                   style: 'bold' },
      { start_ms: 4000, end_ms: 11000, text: '매일 조금씩 성장하는 내가 자랑스러워요!', style: 'highlight' },
      { start_ms: 11000,end_ms: 17000, text: '포기하지 말고 끝까지 달려봐요!',          style: 'bold' },
      { start_ms: 17000,end_ms: 20000, text: '우리 모두 파이팅! 🔥',                   style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 4000,
        type: 'gesture', gesture_id: 'thumbs_up', gesture_emoji: '👍',
        threshold: 0.65, guide_text: '파이팅 포즈!', guide_emoji: '💪', anim_type: 'bounce',
      },
      {
        seq: 2, start_ms: 4000, end_ms: 11500,
        type: 'voice_read',
        read_text: '매일 조금씩 성장하는 내가 자랑스러워요!',
        read_lang: 'ko',
        threshold: 0.55, guide_text: '자신있게 외쳐요!', guide_emoji: '📢', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 11500, end_ms: 17500,
        type: 'voice_read',
        read_text: '포기하지 말고 끝까지 달려봐요!',
        read_lang: 'ko',
        threshold: 0.55, guide_text: '힘차게 말해봐요!', guide_emoji: '🔥', anim_type: 'pulse',
      },
      {
        seq: 4, start_ms: 17500, end_ms: 20000,
        type: 'gesture', gesture_id: 'hands_up', gesture_emoji: '🙌',
        threshold: 0.7, guide_text: '마무리 파이팅!', guide_emoji: '🙌', anim_type: 'bounce',
      },
    ],
  },

  // ─── 10. 아이들 동화 (kids_abc) ───────────────────────────────────────────
  {
    id: 'kids-story-010',
    name: '어린이 동화 읽기',
    genre: 'kids',
    theme_id: 'kids',
    camera_mode: 'selfie',
    difficulty: 1,
    duration_sec: 20,
    bpm: 85,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🌈',
    scene: '어린이도 쉽게 따라 읽는 동화!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #a8edea 0%, #fed6e3 100%)',
      overlayTop: '🌈 동화 세계로!',
      frameColor: '#ff80ab',
    },
    sns_template: {
      hashtags: ['어린이동화', '동화읽기', '키즈챌린지', 'kidsstory', '동화'],
      caption_template: '귀여운 동화 낭독 완료 🌈 {template_name} {score}점! 아이와 함께해요~ #어린이동화 #키즈',
      video_frame_css: 'border: 4px solid #ff80ab; border-radius: 20px;',
    },
    subtitle_timeline: [
      { start_ms: 0,    end_ms: 4000,  text: '🌈 동화 세계로 출발!',       style: 'story' },
      { start_ms: 4000, end_ms: 10000, text: '토끼야, 어디 가니?',          style: 'story' },
      { start_ms: 10000,end_ms: 16000, text: '나는 당근을 찾아가요!',       style: 'story' },
      { start_ms: 16000,end_ms: 20000, text: '모두 함께 행복하게 살았대요!', style: 'story' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 4000,
        type: 'expression',
        threshold: 0.6, guide_text: '신나는 표정!', guide_emoji: '😄', anim_type: 'bounce',
      },
      {
        seq: 2, start_ms: 4000, end_ms: 10500,
        type: 'voice_read',
        read_text: '토끼야, 어디 가니?',
        read_lang: 'ko',
        threshold: 0.5, guide_text: '따라 읽어봐요!', guide_emoji: '🐰', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 10500, end_ms: 16500,
        type: 'voice_read',
        read_text: '나는 당근을 찾아가요!',
        read_lang: 'ko',
        threshold: 0.5, guide_text: '토끼처럼 말해요!', guide_emoji: '🥕', anim_type: 'pulse',
      },
      {
        seq: 4, start_ms: 16500, end_ms: 20000,
        type: 'gesture', gesture_id: 'heart', gesture_emoji: '💕',
        threshold: 0.6, guide_text: '해피엔딩 하트!', guide_emoji: '💕', anim_type: 'pulse',
      },
    ],
  },

  // ─── 11. 스쿼트 챌린지 (fitness-squat) ───────────────────────────────────
  {
    id: 'fitness-squat-001',
    name: '💪 스쿼트 10회 챌린지',
    genre: 'fitness',
    theme_id: 'motivation',
    camera_mode: 'normal',
    difficulty: 2,
    duration_sec: 30,
    bpm: 100,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '💪',
    scene: '카메라 앞에서 스쿼트 10회를 완성하세요! 무릎을 구부려 엉덩이를 낮춰요.',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #f093fb 0%, #f5a623 100%)',
      frameColor: '#f5a623',
    },
    sns_template: {
      hashtags: ['스쿼트챌린지', '홈트', '다이어트', '운동', 'squat'],
      caption_template: '스쿼트 10회 완료! 💪 {template_name} {score}점 달성! #스쿼트챌린지 #홈트',
      video_frame_css: 'border: 3px solid #f5a623; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 3000,  text: '🦶 발을 어깨 너비로 벌리세요!',        style: 'bold' },
      { start_ms: 3000,  end_ms: 10000, text: '⬇️ 1~3번 스쿼트! 천천히 내려가요',     style: 'highlight' },
      { start_ms: 10000, end_ms: 18000, text: '💪 4~7번! 무릎이 발끝을 넘지 않게!',   style: 'bold' },
      { start_ms: 18000, end_ms: 25000, text: '🔥 8~10번! 마지막 힘내요!',            style: 'highlight' },
      { start_ms: 25000, end_ms: 30000, text: '🏆 완료! 승리 포즈!',                  style: 'bold' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 3000,
        type: 'timing',
        threshold: 0.6, guide_text: '준비 자세! 발을 어깨 너비로 벌리세요 🦶', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 3000, end_ms: 10000,
        type: 'timing',
        threshold: 0.65, guide_text: '1~3번 스쿼트! 천천히 내려가요 ⬇️', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 10000, end_ms: 18000,
        type: 'timing',
        threshold: 0.7, guide_text: '4~7번 스쿼트! 무릎이 발끝을 넘지 않게! 💪', anim_type: 'bounce',
      },
      {
        seq: 4, start_ms: 18000, end_ms: 25000,
        type: 'timing',
        threshold: 0.75, guide_text: '8~10번! 마지막 힘내요! 🔥', anim_type: 'shake',
      },
      {
        seq: 5, start_ms: 25000, end_ms: 30000,
        type: 'gesture', gesture_id: 'hands_up', gesture_emoji: '🙌',
        threshold: 0.6, guide_text: '완료! 양손 들어 만세! 🏆', guide_emoji: '🏆', anim_type: 'float',
      },
    ],
  },

  // ─── 12. 플랭크 챌린지 (fitness-plank) ───────────────────────────────────
  {
    id: 'fitness-plank-001',
    name: '🔥 플랭크 30초 챌린지',
    genre: 'fitness',
    theme_id: 'motivation',
    camera_mode: 'normal',
    difficulty: 2,
    duration_sec: 40,
    bpm: 90,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🔥',
    scene: '플랭크 자세로 코어 근육을 강화하세요! 스마트폰 앞에서 도전!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #ff416c 0%, #ff4b2b 100%)',
      frameColor: '#ff4b2b',
    },
    sns_template: {
      hashtags: ['플랭크챌린지', '코어운동', '홈트', '30초플랭크', 'plank'],
      caption_template: '플랭크 30초 성공! 🔥 {template_name} {score}점! 코어 완성! #플랭크챌린지 #홈트',
      video_frame_css: 'border: 3px solid #ff4b2b; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 5000,  text: '🙌 팔 뻗기 준비 자세!',        style: 'bold' },
      { start_ms: 5000,  end_ms: 20000, text: '💪 플랭크 15초! 버텨요! 코어 긴장!', style: 'highlight' },
      { start_ms: 20000, end_ms: 35000, text: '🔥 아직 15초 더! 포기하지 마세요!', style: 'bold' },
      { start_ms: 35000, end_ms: 40000, text: '🎉 30초 완료! 최고야!',          style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 5000,
        type: 'gesture', gesture_id: 'arms_spread', gesture_emoji: '🙌',
        threshold: 0.6, guide_text: '팔 뻗기 준비 자세!', anim_type: 'bounce',
      },
      {
        seq: 2, start_ms: 5000, end_ms: 20000,
        type: 'timing',
        threshold: 0.7, guide_text: '플랭크 15초! 버텨요! 💪 코어 긴장!', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 20000, end_ms: 35000,
        type: 'timing',
        threshold: 0.75, guide_text: '아직 15초 더! 포기하지 마세요! 🔥', anim_type: 'shake',
      },
      {
        seq: 4, start_ms: 35000, end_ms: 40000,
        type: 'expression',
        threshold: 0.6, guide_text: '🎉 30초 완료! 최고야!', guide_emoji: '🎉', anim_type: 'float',
      },
    ],
  },

  // ─── 13. K-POP 댄스 챌린지 (dance-kpop) ─────────────────────────────────
  {
    id: 'dance-kpop-001',
    name: '💃 K-POP 댄스 챌린지',
    genre: 'kpop',
    theme_id: 'kpop',
    camera_mode: 'selfie',
    difficulty: 3,
    duration_sec: 30,
    bpm: 128,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '💃',
    scene: 'K-POP 리듬에 맞춰 댄스 챌린지! 개성있는 움직임을 보여주세요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'pattern',
      css: 'linear-gradient(135deg, #0f0c29 0%, #302b63 50%, #24243e 100%)',
      overlayTop: '💃 K-POP DANCE CHALLENGE',
      frameColor: '#e94560',
    },
    sns_template: {
      hashtags: ['kpop댄스챌린지', 'kpopdance', '케이팝댄스', '댄스챌린지', 'kpop'],
      caption_template: 'K-POP 댄스 챌린지 완료! 💃 {template_name} {score}점! 같이 춰요~ #kpop #댄스챌린지',
      video_frame_css: 'border: 3px solid #e94560; border-radius: 12px; background: #0f0c29;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 5000,  text: '👋 리듬에 맞춰 손 흔들기!',      style: 'highlight' },
      { start_ms: 5000,  end_ms: 12000, text: '🎵 온몸으로 리듬타기! 자유롭게!', style: 'bold' },
      { start_ms: 12000, end_ms: 18000, text: '🙌 팔 벌려 에너지 업!',           style: 'highlight' },
      { start_ms: 18000, end_ms: 25000, text: '🌟 최고 하이라이트! 최선을 다해요!', style: 'bold' },
      { start_ms: 25000, end_ms: 30000, text: '👍 마무리 포즈!',                 style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 5000,
        type: 'gesture', gesture_id: 'wave', gesture_emoji: '👋',
        threshold: 0.6, guide_text: '리듬에 맞춰 손 흔들기!', guide_emoji: '👋', anim_type: 'float',
      },
      {
        seq: 2, start_ms: 5000, end_ms: 12000,
        type: 'timing',
        threshold: 0.6, guide_text: '온몸으로 리듬타기! 🎵 자유롭게!', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 12000, end_ms: 18000,
        type: 'gesture', gesture_id: 'arms_spread', gesture_emoji: '🙌',
        threshold: 0.65, guide_text: '팔 벌려 에너지 업!', guide_emoji: '🙌', anim_type: 'spin',
      },
      {
        seq: 4, start_ms: 18000, end_ms: 25000,
        type: 'timing',
        threshold: 0.65, guide_text: '최고 하이라이트! 최선을 다해요! 🌟', anim_type: 'shake',
      },
      {
        seq: 5, start_ms: 25000, end_ms: 30000,
        type: 'gesture', gesture_id: 'thumbs_up', gesture_emoji: '👍',
        threshold: 0.6, guide_text: '마무리 포즈!', guide_emoji: '👍', anim_type: 'bounce',
      },
    ],
  },

  // ─── 14. 자세 교정 챌린지 (posture-correct) ──────────────────────────────
  {
    id: 'posture-correct-001',
    name: '🧘 바른 자세 챌린지',
    genre: 'fitness',
    theme_id: 'motivation',
    camera_mode: 'normal',
    difficulty: 1,
    duration_sec: 20,
    bpm: 70,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🧘',
    scene: '앉아서 또는 서서 올바른 자세를 30초 유지하세요! 척추 건강을 지켜요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #43cea2 0%, #185a9d 100%)',
      frameColor: '#43cea2',
    },
    sns_template: {
      hashtags: ['바른자세챌린지', '자세교정', '척추건강', '홈트', 'posture'],
      caption_template: '바른 자세 챌린지 성공! 🧘 {template_name} {score}점! 척추 건강 지켜요~ #바른자세 #자세교정',
      video_frame_css: 'border: 3px solid #43cea2; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 5000,  text: '💆 등을 쭉 펴고 앉아요! 어깨를 펴세요',       style: 'bold' },
      { start_ms: 5000,  end_ms: 12000, text: '👀 턱을 당기고 고개를 바로! 눈높이 맞춰요',   style: 'highlight' },
      { start_ms: 12000, end_ms: 20000, text: '🌟 이 자세 유지! 코어 긴장! 완벽한 자세예요', style: 'bold' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 5000,
        type: 'timing',
        threshold: 0.6, guide_text: '등을 쭉 펴고 앉아요! 어깨를 펴세요 💆', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 5000, end_ms: 12000,
        type: 'timing',
        threshold: 0.65, guide_text: '턱을 당기고 고개를 바로! 모니터와 눈높이 맞춰요 👀', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 12000, end_ms: 20000,
        type: 'timing',
        threshold: 0.7, guide_text: '이 자세 유지! 코어 긴장! 완벽한 자세예요 🌟', anim_type: 'float',
      },
    ],
  },

  // ─── 15. 영어 발음 챌린지 (english-speak) ────────────────────────────────
  {
    id: 'english-speak-001',
    name: '🌍 영어 발음 마스터',
    genre: 'english',
    theme_id: 'english',
    camera_mode: 'selfie',
    difficulty: 2,
    duration_sec: 25,
    bpm: 90,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🎓',
    scene: '영어 문장을 크게 따라 읽어봐요! 발음 연습 챌린지!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #2193b0 0%, #6dd5ed 100%)',
      overlayTop: '🎓 English Pronunciation Master',
      frameColor: '#2193b0',
    },
    sns_template: {
      hashtags: ['영어발음챌린지', '영어공부', '발음연습', 'englishpronunciation', '영어마스터'],
      caption_template: '영어 발음 마스터 도전! 🌍 {template_name} {score}점! 나도 영어 잘해! #영어발음챌린지',
      video_frame_css: 'border: 3px solid #2193b0; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 8000,  text: 'Hello! My name is Challenge Master!', style: 'highlight' },
      { start_ms: 8000,  end_ms: 17000, text: 'I love learning English every day!',  style: 'highlight' },
      { start_ms: 17000, end_ms: 25000, text: 'Challenge accepted and completed!',   style: 'bold' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 8000,
        type: 'voice_read',
        read_text: 'Hello! My name is Challenge Master!',
        read_lang: 'en',
        threshold: 0.6, guide_text: 'Hello! My name is Challenge Master!', guide_emoji: '🗣️', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 8000, end_ms: 17000,
        type: 'voice_read',
        read_text: 'I love learning English every day!',
        read_lang: 'en',
        threshold: 0.6, guide_text: 'I love learning English every day!', guide_emoji: '📚', anim_type: 'pulse',
      },
      {
        seq: 3, start_ms: 17000, end_ms: 25000,
        type: 'voice_read',
        read_text: 'Challenge accepted and completed!',
        read_lang: 'en',
        threshold: 0.65, guide_text: 'Challenge accepted and completed!', guide_emoji: '🏆', anim_type: 'bounce',
      },
    ],
  },

  // ─── 16. 명상 챌린지 (meditation) ────────────────────────────────────────
  {
    id: 'meditation-001',
    name: '🧘 명상 챌린지',
    genre: 'fitness',
    theme_id: 'motivation',
    camera_mode: 'selfie',
    difficulty: 1,
    duration_sec: 30,
    bpm: 60,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🌸',
    scene: '눈을 감고 깊게 호흡해요. 마음을 고요히 하는 30초 챌린지!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #a18cd1 0%, #fbc2eb 100%)',
      frameColor: '#a18cd1',
    },
    sns_template: {
      hashtags: ['명상챌린지', '마음챙김', '호흡명상', 'meditation', '힐링'],
      caption_template: '명상 챌린지 완료! 🌸 {template_name} {score}점! 마음이 편안해졌어요 #명상챌린지 #힐링',
      video_frame_css: 'border: 3px solid #a18cd1; border-radius: 16px;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 10000, text: '🌬️ 눈 감고 깊게 숨 들이쉬기... 4초',   style: 'bold' },
      { start_ms: 10000, end_ms: 20000, text: '😌 7초 참기... 차분하게 유지',           style: 'normal' },
      { start_ms: 20000, end_ms: 30000, text: '✨ 8초 내쉬기... 평온한 마음으로 완료!', style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 10000,
        type: 'timing',
        threshold: 0.6, guide_text: '눈 감고 깊게 숨 들이쉬기 🌬️ 4초 들이쉬고', anim_type: 'float',
      },
      {
        seq: 2, start_ms: 10000, end_ms: 20000,
        type: 'timing',
        threshold: 0.6, guide_text: '7초 참기... 차분하게 유지 😌', anim_type: 'float',
      },
      {
        seq: 3, start_ms: 20000, end_ms: 30000,
        type: 'expression',
        threshold: 0.6, guide_text: '8초 내쉬기 & 평온한 표정 유지 ✨', guide_emoji: '✨', anim_type: 'pulse',
      },
    ],
  },

  // ─── 17. 팔굽혀펴기 챌린지 (fitness-pushup) ──────────────────────────────
  {
    id: 'fitness-pushup-001',
    name: '💪 팔굽혀펴기 챌린지',
    genre: 'fitness',
    theme_id: 'motivation',
    camera_mode: 'normal',
    difficulty: 3,
    duration_sec: 35,
    bpm: 95,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🦾',
    scene: '스마트폰 앞에서 팔굽혀펴기 10회! 상체 근력을 키워요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #1c1c1c 0%, #3a3a3a 50%, #1a1a2e 100%)',
      overlayTop: '🦾 PUSH-UP CHALLENGE',
      frameColor: '#e94560',
    },
    sns_template: {
      hashtags: ['팔굽혀펴기챌린지', '푸시업', '상체운동', '홈트', 'pushup'],
      caption_template: '팔굽혀펴기 10회 완료! 💪 {template_name} {score}점! 상체 완성! #팔굽혀펴기 #홈트',
      video_frame_css: 'border: 3px solid #e94560; border-radius: 12px; background: #1c1c1c;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 5000,  text: '🙌 준비 자세! 팔은 어깨 너비로',          style: 'bold' },
      { start_ms: 5000,  end_ms: 15000, text: '💪 1~4번! 가슴이 바닥에 닿을 듯이!',     style: 'highlight' },
      { start_ms: 15000, end_ms: 25000, text: '🔥 5~8번! 포기하지 마세요!',              style: 'bold' },
      { start_ms: 25000, end_ms: 35000, text: '💥 9~10번! 마지막 힘내요!',              style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 5000,
        type: 'timing',
        threshold: 0.6, guide_text: '준비 자세! 팔은 어깨 너비로 🙌', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 5000, end_ms: 15000,
        type: 'timing',
        threshold: 0.7, guide_text: '1~4번! 가슴이 바닥에 닿을 듯이! 💪', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 15000, end_ms: 25000,
        type: 'timing',
        threshold: 0.72, guide_text: '5~8번! 포기하지 마세요! 🔥', anim_type: 'shake',
      },
      {
        seq: 4, start_ms: 25000, end_ms: 35000,
        type: 'timing',
        threshold: 0.75, guide_text: '9~10번! 마지막 힘내요! 💥', anim_type: 'shake',
      },
    ],
  },

  // ─── 18. 힙합 댄스 챌린지 (dance-hiphop) ────────────────────────────────
  {
    id: 'dance-hiphop-001',
    name: '🎵 힙합 댄스 챌린지',
    genre: 'hiphop',
    theme_id: 'kpop',
    camera_mode: 'selfie',
    difficulty: 2,
    duration_sec: 25,
    bpm: 95,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🎤',
    scene: '힙합 비트에 맞춰 자유롭게 춤춰요! 나만의 스타일을 보여주세요!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'pattern',
      css: 'linear-gradient(135deg, #0f0c29 0%, #1a1a2e 50%, #24243e 100%)',
      overlayTop: '🎤 HIPHOP DANCE CHALLENGE',
      frameColor: '#f7b731',
    },
    sns_template: {
      hashtags: ['힙합댄스챌린지', '힙합', '댄스챌린지', 'hiphop', 'freestyle'],
      caption_template: '힙합 댄스 챌린지 완료! 🎵 {template_name} {score}점! 내 스타일 봐봐~ #힙합 #댄스챌린지',
      video_frame_css: 'border: 3px solid #f7b731; border-radius: 12px; background: #0f0c29;',
    },
    subtitle_timeline: [
      { start_ms: 0,     end_ms: 6000,  text: '👍 엄지척으로 입장!',          style: 'bold' },
      { start_ms: 6000,  end_ms: 14000, text: '🎵 비트에 맞춰 자유롭게! 헤드바운싱!', style: 'highlight' },
      { start_ms: 14000, end_ms: 20000, text: '🤜 팔 교차 동작!',             style: 'bold' },
      { start_ms: 20000, end_ms: 25000, text: '😎 마무리 쿨 포즈!',           style: 'highlight' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 6000,
        type: 'gesture', gesture_id: 'thumbs_up', gesture_emoji: '👍',
        threshold: 0.6, guide_text: '엄지척으로 입장!', guide_emoji: '👍', anim_type: 'bounce',
      },
      {
        seq: 2, start_ms: 6000, end_ms: 14000,
        type: 'timing',
        threshold: 0.6, guide_text: '비트에 맞춰 자유롭게! 헤드바운싱! 🎵', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 14000, end_ms: 20000,
        type: 'gesture', gesture_id: 'arms_cross', gesture_emoji: '🤜',
        threshold: 0.65, guide_text: '팔 교차 동작!', guide_emoji: '🤜', anim_type: 'spin',
      },
      {
        seq: 4, start_ms: 20000, end_ms: 25000,
        type: 'expression',
        threshold: 0.6, guide_text: '마무리 쿨 포즈! 😎', guide_emoji: '😎', anim_type: 'float',
      },
    ],
  },

  // ─── 19. 스쿼트 50개 챌린지 (fitness-squat-50) ────────────────────────────
  {
    id: 'fitness-squat-50',
    name: '🏆 스쿼트 50개 챌린지',
    genre: 'fitness',
    theme_id: 'motivation',
    camera_mode: 'normal',
    difficulty: 3,
    duration_sec: 120,
    bpm: 110,
    bgm_url: '',
    thumbnail_url: '',
    theme_emoji: '🏆',
    scene: '스쿼트 50개에 도전! 꾸준히 하면 살이 빠지고 근육이 생겨요. 하루 1세트부터 시작!',
    created_at: new Date().toISOString(),
    virtual_bg: {
      type: 'gradient',
      css: 'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
      overlayTop: '🏆 SQUAT 50 CHALLENGE',
      overlayBottom: '#스쿼트50개  #홈트  #다이어트  #하체운동  #squat50challenge  #홈트레이닝',
      frameColor: '#14b8a6',
    },
    sns_template: {
      hashtags: ['스쿼트50개', '스쿼트챌린지', '홈트', '하체운동', '다이어트운동', 'squat50'],
      caption_template: '스쿼트 50개 달성! 🏆 {template_name} {score}점! 같이 도전해봐요~ #스쿼트50개 #홈트',
      video_frame_css: 'border: 3px solid #14b8a6; border-radius: 12px;',
    },
    subtitle_timeline: [
      { start_ms: 0,      end_ms: 8000,   text: '🦶 발을 어깨 너비로! 준비 자세 잡아요', style: 'bold' },
      { start_ms: 8000,   end_ms: 28000,  text: '⬇️ 1~10개! 천천히 내려가고 올라와요', style: 'highlight' },
      { start_ms: 28000,  end_ms: 50000,  text: '💪 11~20개! 무릎이 발끝 안쪽으로!', style: 'bold' },
      { start_ms: 50000,  end_ms: 70000,  text: '🔥 21~30개! 절반! 포기하지 마세요!', style: 'highlight' },
      { start_ms: 70000,  end_ms: 90000,  text: '💥 31~40개! 엉덩이 더 내려요!', style: 'bold' },
      { start_ms: 90000,  end_ms: 108000, text: '🌟 41~50개! 마지막! 최선을 다해요!', style: 'highlight' },
      { start_ms: 108000, end_ms: 120000, text: '🏆 완료! 50개 달성! 당신은 최고야!', style: 'bold' },
    ],
    missions: [
      {
        seq: 1, start_ms: 0, end_ms: 8000,
        type: 'timing',
        threshold: 0.6,
        guide_text: '발을 어깨 너비로 벌려요! 준비 자세 💪',
        guide_emoji: '🦶', anim_type: 'pulse',
      },
      {
        seq: 2, start_ms: 8000, end_ms: 28000,
        type: 'timing',
        threshold: 0.65,
        guide_text: '1~10개! 무릎을 90° 굽혀요 ⬇️',
        guide_emoji: '🏋️', anim_type: 'bounce',
      },
      {
        seq: 3, start_ms: 28000, end_ms: 50000,
        type: 'timing',
        threshold: 0.70,
        guide_text: '11~20개! 엉덩이를 낮게! 💪',
        guide_emoji: '🔥', anim_type: 'bounce',
      },
      {
        seq: 4, start_ms: 50000, end_ms: 70000,
        type: 'timing',
        threshold: 0.72,
        guide_text: '21~30개! 절반 달성! 포기 금지! 🔥',
        guide_emoji: '💥', anim_type: 'shake',
      },
      {
        seq: 5, start_ms: 70000, end_ms: 90000,
        type: 'timing',
        threshold: 0.75,
        guide_text: '31~40개! 무릎 발끝 안쪽! 💥',
        guide_emoji: '💪', anim_type: 'shake',
      },
      {
        seq: 6, start_ms: 90000, end_ms: 108000,
        type: 'timing',
        threshold: 0.78,
        guide_text: '41~50개! 마지막 스퍼트! 🌟',
        guide_emoji: '🌟', anim_type: 'bounce',
      },
      {
        seq: 7, start_ms: 108000, end_ms: 120000,
        type: 'gesture', gesture_id: 'hands_up', gesture_emoji: '🙌',
        threshold: 0.6, guide_text: '50개 완료! 만세 포즈! 🏆', guide_emoji: '🏆', anim_type: 'float',
      },
    ],
  },
];

export const MOCK_USER_ID = 'mock-user-0001';

export const MOCK_PROFILE: UserProfile = {
  user_id: MOCK_USER_ID,
  preferred_genres: ['daily', 'kpop', 'travel', 'kids', 'news'],
  success_rates: {
    'daily-vlog-001':   0.82,
    'kpop-challenge-007': 0.75,
    'travel-cert-005':  0.68,
  },
  total_sessions: 8,
  weak_joints: ['left_wrist', 'right_wrist'],
};

export const MOCK_SESSIONS: UserSession[] = [
  {
    id: 'session-001',
    user_id: MOCK_USER_ID,
    template_id: 'daily-vlog-001',
    recorded_at: new Date(Date.now() - 86400000).toISOString(),
    avg_score: 0.82,
    success_rate: 0.80,
    tag_timeline: [],
    video_url: null,
    edited_video_url: null,
  },
  {
    id: 'session-002',
    user_id: MOCK_USER_ID,
    template_id: 'kpop-challenge-007',
    recorded_at: new Date(Date.now() - 172800000).toISOString(),
    avg_score: 0.71,
    success_rate: 0.75,
    tag_timeline: [],
    video_url: null,
    edited_video_url: null,
  },
  {
    id: 'session-003',
    user_id: MOCK_USER_ID,
    template_id: 'news-anchor-002',
    recorded_at: new Date(Date.now() - 259200000).toISOString(),
    avg_score: 0.65,
    success_rate: 0.70,
    tag_timeline: [],
    video_url: null,
    edited_video_url: null,
  },
];
