/**
 * videoTemplates.ts — 사전 정의된 CapCut 스타일 비디오 템플릿
 * 각 템플릿은 clip_slots (사용자 촬영분이 들어갈 자리)와
 * text_overlays (자동 삽입되는 텍스트/자막)를 정의
 */
import type { VideoTemplate } from './videoCompositor';

export const VIDEO_TEMPLATES: VideoTemplate[] = [
  // ── 1. 일상 브이로그 (60초) ──────────────────────────────
  {
    id: 'vt-vlog',
    name: '일상 브이로그',
    duration_ms: 60000,
    aspect_ratio: '9:16',
    background: 'linear-gradient(135deg, #667eea, #764ba2)',
    hashtags: ['브이로그', '일상', 'vlog', 'daily'],
    caption_template: '오늘의 일상 브이로그 🎬 {score}점 달성! {hashtags}',
    clip_slots: [
      {
        id: 'intro',
        start_ms: 0,
        end_ms: 8000,
        x: 0,
        y: 0.05,
        width: 1,
        height: 0.5,
        effect: 'fade_in',
        border_color: '#9b59b6',
        label: '인사 클립',
      },
      {
        id: 'daily1',
        start_ms: 8000,
        end_ms: 22000,
        x: 0,
        y: 0,
        width: 0.5,
        height: 0.48,
        border_radius: 12,
        effect: 'zoom_in',
        label: '일상 클립 1',
      },
      {
        id: 'daily2',
        start_ms: 8000,
        end_ms: 22000,
        x: 0.5,
        y: 0,
        width: 0.5,
        height: 0.48,
        border_radius: 12,
        effect: 'zoom_in',
        label: '일상 클립 2',
      },
      {
        id: 'main',
        start_ms: 22000,
        end_ms: 45000,
        x: 0,
        y: 0,
        width: 1,
        height: 0.65,
        effect: 'zoom_in',
        label: '메인 클립',
      },
      {
        id: 'outro',
        start_ms: 45000,
        end_ms: 60000,
        x: 0,
        y: 0,
        width: 1,
        height: 0.6,
        effect: 'fade_in',
        border_color: '#e94560',
        label: '마무리 클립',
      },
    ],
    text_overlays: [
      {
        start_ms: 500,
        end_ms: 4000,
        text: '✨ 오늘의 브이로그',
        x: 0.5,
        y: 0.62,
        font_size: 32,
        color: '#fff',
        align: 'center',
        animation: 'slide_up',
        weight: 'bold',
        bg_color: 'rgba(0,0,0,0.5)',
      },
      {
        start_ms: 4000,
        end_ms: 8000,
        text: '📱 오늘도 좋은 하루!',
        x: 0.5,
        y: 0.66,
        font_size: 24,
        color: '#ffd700',
        align: 'center',
        animation: 'fade',
      },
      {
        start_ms: 8000,
        end_ms: 22000,
        text: '🌟 일상 하이라이트',
        x: 0.5,
        y: 0.52,
        font_size: 22,
        color: '#fff',
        align: 'center',
        animation: 'fade',
        bg_color: 'rgba(155,89,182,0.7)',
      },
      {
        start_ms: 22000,
        end_ms: 45000,
        text: '💫 오늘의 메인 장면',
        x: 0.5,
        y: 0.72,
        font_size: 28,
        color: '#fff',
        align: 'center',
        animation: 'bounce',
      },
      {
        start_ms: 45000,
        end_ms: 55000,
        text: '❤️ 구독과 좋아요!',
        x: 0.5,
        y: 0.68,
        font_size: 30,
        color: '#ff6b6b',
        align: 'center',
        animation: 'bounce',
        weight: 'bold',
      },
      {
        start_ms: 55000,
        end_ms: 60000,
        text: '📺 다음 편도 기대해주세요~',
        x: 0.5,
        y: 0.72,
        font_size: 22,
        color: '#fff',
        align: 'center',
        animation: 'fade',
      },
    ],
  },

  // ── 2. 뉴스 앵커 (90초) ──────────────────────────────────
  {
    id: 'vt-news',
    name: '뉴스 앵커 챌린지',
    duration_ms: 90000,
    aspect_ratio: '9:16',
    background: 'linear-gradient(180deg, #0a1628, #1a2e4a)',
    hashtags: ['뉴스앵커', '아나운서', 'news', '챌린지'],
    caption_template: '📺 나도 뉴스 앵커! {score}점 달성 {hashtags}',
    clip_slots: [
      {
        id: 'open',
        start_ms: 0,
        end_ms: 15000,
        x: 0.1,
        y: 0.08,
        width: 0.8,
        height: 0.55,
        border_radius: 8,
        border_color: '#1565c0',
        effect: 'fade_in',
        label: '오프닝',
      },
      {
        id: 'news1',
        start_ms: 15000,
        end_ms: 45000,
        x: 0,
        y: 0.06,
        width: 1,
        height: 0.6,
        effect: 'zoom_in',
        label: '뉴스 읽기 1',
      },
      {
        id: 'news2',
        start_ms: 45000,
        end_ms: 75000,
        x: 0,
        y: 0.06,
        width: 1,
        height: 0.6,
        effect: 'zoom_in',
        label: '뉴스 읽기 2',
      },
      {
        id: 'close',
        start_ms: 75000,
        end_ms: 90000,
        x: 0.1,
        y: 0.08,
        width: 0.8,
        height: 0.55,
        border_radius: 8,
        border_color: '#1565c0',
        effect: 'fade_in',
        label: '클로징',
      },
    ],
    text_overlays: [
      {
        start_ms: 0,
        end_ms: 15000,
        text: '📺 LIVE NEWS',
        x: 0.5,
        y: 0.68,
        font_size: 36,
        color: '#fff',
        align: 'center',
        animation: 'fade',
        weight: 'bold',
        bg_color: 'rgba(21,101,192,0.9)',
      },
      {
        start_ms: 0,
        end_ms: 90000,
        text: '🔴 속보 · 오늘의 뉴스 · BREAKING NEWS · 최신 뉴스 · 속보 · 오늘의 뉴스 ·',
        x: 0.5,
        y: 0.95,
        font_size: 14,
        color: '#fff',
        align: 'center',
        bg_color: 'rgba(21,101,192,0.95)',
      },
      {
        start_ms: 15000,
        end_ms: 45000,
        text: '📋 오늘의 주요 뉴스',
        x: 0.5,
        y: 0.7,
        font_size: 20,
        color: '#ffd700',
        align: 'center',
        animation: 'slide_up',
        bg_color: 'rgba(0,0,0,0.7)',
      },
      {
        start_ms: 45000,
        end_ms: 75000,
        text: '🌤️ 날씨 뉴스',
        x: 0.5,
        y: 0.7,
        font_size: 20,
        color: '#87ceeb',
        align: 'center',
        animation: 'slide_up',
        bg_color: 'rgba(0,0,0,0.7)',
      },
      {
        start_ms: 75000,
        end_ms: 90000,
        text: '👋 오늘의 뉴스를 마칩니다',
        x: 0.5,
        y: 0.7,
        font_size: 20,
        color: '#fff',
        align: 'center',
        animation: 'fade',
        bg_color: 'rgba(21,101,192,0.8)',
      },
    ],
  },

  // ── 3. K-POP 챌린지 (60초) ───────────────────────────────
  {
    id: 'vt-kpop',
    name: 'K-POP 댄스 챌린지',
    duration_ms: 60000,
    aspect_ratio: '9:16',
    background: 'linear-gradient(135deg, #1a1a2e, #0f3460)',
    hashtags: ['kpop', 'kpopchallenge', '댄스챌린지', '아이돌'],
    caption_template: '🎤 K-POP 챌린지 {score}점! {hashtags}',
    clip_slots: [
      {
        id: 'ready',
        start_ms: 0,
        end_ms: 8000,
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        effect: 'fade_in',
        label: '준비',
      },
      {
        id: 'dance1',
        start_ms: 8000,
        end_ms: 25000,
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        effect: 'zoom_in',
        label: '댄스 파트 1',
      },
      {
        id: 'dance2',
        start_ms: 25000,
        end_ms: 45000,
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        effect: 'zoom_in',
        label: '댄스 파트 2',
      },
      {
        id: 'finale',
        start_ms: 45000,
        end_ms: 60000,
        x: 0,
        y: 0,
        width: 1,
        height: 1,
        effect: 'fade_in',
        label: '피날레',
      },
    ],
    text_overlays: [
      {
        start_ms: 0,
        end_ms: 8000,
        text: '🎤 K-POP CHALLENGE',
        x: 0.5,
        y: 0.15,
        font_size: 34,
        color: '#e94560',
        align: 'center',
        animation: 'bounce',
        weight: 'bold',
      },
      {
        start_ms: 8000,
        end_ms: 25000,
        text: '🕺 파트 1',
        x: 0.5,
        y: 0.9,
        font_size: 22,
        color: '#fff',
        align: 'center',
        animation: 'fade',
        bg_color: 'rgba(233,69,96,0.8)',
      },
      {
        start_ms: 25000,
        end_ms: 45000,
        text: '💃 파트 2',
        x: 0.5,
        y: 0.9,
        font_size: 22,
        color: '#fff',
        align: 'center',
        animation: 'fade',
        bg_color: 'rgba(233,69,96,0.8)',
      },
      {
        start_ms: 45000,
        end_ms: 55000,
        text: '✨ PERFECT ENDING!',
        x: 0.5,
        y: 0.12,
        font_size: 30,
        color: '#ffd700',
        align: 'center',
        animation: 'bounce',
        weight: 'bold',
      },
      {
        start_ms: 55000,
        end_ms: 60000,
        text: '🎤 구독 & 좋아요 ❤️',
        x: 0.5,
        y: 0.88,
        font_size: 24,
        color: '#fff',
        align: 'center',
        animation: 'slide_up',
        bg_color: 'rgba(233,69,96,0.9)',
      },
    ],
  },

  // ── 4. 영어 스피킹 (75초) ────────────────────────────────
  {
    id: 'vt-english',
    name: '영어 스피킹 챌린지',
    duration_ms: 75000,
    aspect_ratio: '9:16',
    background: 'linear-gradient(135deg, #f5f7fa, #c3cfe2)',
    hashtags: ['영어챌린지', 'EnglishChallenge', '영어공부', 'speaking'],
    caption_template: '🇺🇸 영어 스피킹 {score}점! {hashtags}',
    clip_slots: [
      {
        id: 'intro',
        start_ms: 0,
        end_ms: 12000,
        x: 0.05,
        y: 0.1,
        width: 0.9,
        height: 0.5,
        border_radius: 16,
        border_color: '#2196f3',
        effect: 'fade_in',
        label: '인트로',
      },
      {
        id: 'sent1',
        start_ms: 12000,
        end_ms: 34000,
        x: 0,
        y: 0.05,
        width: 1,
        height: 0.65,
        effect: 'zoom_in',
        label: '문장 1',
      },
      {
        id: 'sent2',
        start_ms: 34000,
        end_ms: 58000,
        x: 0,
        y: 0.05,
        width: 1,
        height: 0.65,
        effect: 'zoom_in',
        label: '문장 2',
      },
      {
        id: 'outro',
        start_ms: 58000,
        end_ms: 75000,
        x: 0.05,
        y: 0.1,
        width: 0.9,
        height: 0.5,
        border_radius: 16,
        border_color: '#2196f3',
        effect: 'fade_in',
        label: '마무리',
      },
    ],
    text_overlays: [
      {
        start_ms: 0,
        end_ms: 12000,
        text: '🇺🇸 English Speaking',
        x: 0.5,
        y: 0.68,
        font_size: 28,
        color: '#2196f3',
        align: 'center',
        animation: 'slide_up',
        weight: 'bold',
      },
      {
        start_ms: 12000,
        end_ms: 34000,
        text: '"Hello everyone! Today is a wonderful day."',
        x: 0.5,
        y: 0.76,
        font_size: 18,
        color: '#333',
        align: 'center',
        animation: 'fade',
        bg_color: 'rgba(33,150,243,0.12)',
      },
      {
        start_ms: 34000,
        end_ms: 58000,
        text: '"I love learning English every single day!"',
        x: 0.5,
        y: 0.76,
        font_size: 18,
        color: '#333',
        align: 'center',
        animation: 'fade',
        bg_color: 'rgba(33,150,243,0.12)',
      },
      {
        start_ms: 58000,
        end_ms: 75000,
        text: '🏆 챌린지 완료!',
        x: 0.5,
        y: 0.68,
        font_size: 30,
        color: '#2196f3',
        align: 'center',
        animation: 'bounce',
        weight: 'bold',
      },
    ],
  },

  // ── 5. 동화책 읽기 (80초) ────────────────────────────────
  {
    id: 'vt-fairy',
    name: '동화책 읽기',
    duration_ms: 80000,
    aspect_ratio: '9:16',
    background: 'linear-gradient(135deg, #ffecd2, #fcb69f)',
    hashtags: ['동화읽기', '독서챌린지', '동화', 'fairytale'],
    caption_template: '📖 동화책 읽기 챌린지 {score}점! {hashtags}',
    clip_slots: [
      {
        id: 'open',
        start_ms: 0,
        end_ms: 10000,
        x: 0.1,
        y: 0.05,
        width: 0.8,
        height: 0.55,
        border_radius: 20,
        border_color: '#ff9800',
        effect: 'fade_in',
        label: '시작',
      },
      {
        id: 'story1',
        start_ms: 10000,
        end_ms: 35000,
        x: 0,
        y: 0.02,
        width: 1,
        height: 0.62,
        effect: 'zoom_in',
        label: '이야기 1',
      },
      {
        id: 'story2',
        start_ms: 35000,
        end_ms: 65000,
        x: 0,
        y: 0.02,
        width: 1,
        height: 0.62,
        effect: 'zoom_in',
        label: '이야기 2',
      },
      {
        id: 'end',
        start_ms: 65000,
        end_ms: 80000,
        x: 0.1,
        y: 0.05,
        width: 0.8,
        height: 0.55,
        border_radius: 20,
        border_color: '#ff9800',
        effect: 'fade_in',
        label: '마무리',
      },
    ],
    text_overlays: [
      {
        start_ms: 0,
        end_ms: 10000,
        text: '📖 옛날 옛적에...',
        x: 0.5,
        y: 0.65,
        font_size: 28,
        color: '#7b3f00',
        align: 'center',
        animation: 'fade',
        weight: 'bold',
      },
      {
        start_ms: 10000,
        end_ms: 35000,
        text: '🌲 숲속 오두막 이야기',
        x: 0.5,
        y: 0.68,
        font_size: 20,
        color: '#5d4037',
        align: 'center',
        animation: 'slide_up',
        bg_color: 'rgba(255,152,0,0.25)',
      },
      {
        start_ms: 35000,
        end_ms: 65000,
        text: '🐰 귀여운 토끼 이야기',
        x: 0.5,
        y: 0.68,
        font_size: 20,
        color: '#5d4037',
        align: 'center',
        animation: 'slide_up',
        bg_color: 'rgba(255,152,0,0.25)',
      },
      {
        start_ms: 65000,
        end_ms: 80000,
        text: '🌸 행복하게 살았답니다 🌸',
        x: 0.5,
        y: 0.65,
        font_size: 22,
        color: '#7b3f00',
        align: 'center',
        animation: 'bounce',
        weight: 'bold',
      },
    ],
  },
];

export function getVideoTemplate(id: string): VideoTemplate | undefined {
  return VIDEO_TEMPLATES.find((t) => t.id === id);
}

export function getTemplateByMissionId(missionTemplateId: string): VideoTemplate {
  const map: Record<string, string> = {
    vlog: 'vt-vlog',
    daily: 'vt-vlog',
    news: 'vt-news',
    kpop: 'vt-kpop',
    kpop_challenge: 'vt-kpop',
    english: 'vt-english',
    english_lesson: 'vt-english',
    fairy_tale: 'vt-fairy',
    kids: 'vt-fairy',
  };
  const vtId = map[missionTemplateId] ?? 'vt-vlog';
  return VIDEO_TEMPLATES.find((t) => t.id === vtId) ?? VIDEO_TEMPLATES[0];
}
